# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20180304_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_upload',
            new_name='image',
        ),
    ]
