# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180305_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='allow_annony',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
